"""
Action Resources — Official Government URL Whitelist & Action Definitions
==========================================================================

This module provides a backend-owned whitelist of verified official
government destinations and internal application actions.

SECURITY:
- URLs are NEVER generated by LLM
- URLs are NEVER provided by frontend
- Only whitelisted action IDs are accepted
- Unknown action IDs are rejected/filtered

"""
from typing import Dict, Set, Optional, List
from pydantic import BaseModel


# ────────────────────────────────────────────────────────────────────────────
# OFFICIAL GOVERNMENT DESTINATIONS
# ────────────────────────────────────────────────────────────────────────────

OFFICIAL_DESTINATIONS: Dict[str, str] = {
    # Indian Patent Office - IP India
    "patent_search": "https://ipindiaonline.gov.in/epatentSearch/",
    "patent_filing": "https://ipindiaonline.gov.in/",
    "patent_forms": "https://ipindia.gov.in/patents-before-you-apply-forms-official-fees",
    "ip_india_manual": "https://ipindia.gov.in/writereaddata/Portal/IPOGuidelinesManuals/1_101_1_MANUAL_FOR_PATENT_OFFICE_PRACTICE_AND_PROCEDURE_.pdf",

    # National Biodiversity Authority
    "nba_resources": "https://nbaindia.org/",
    "nba_access_guidelines": "https://nbaindia.org/content/703/28/1/access.html",

    # FSSAI - Food Safety and Standards Authority of India
    "foscos": "https://foscos.fssai.gov.in/",
    "fssai_regulations": "https://www.fssai.gov.in/cms/food-safety-and-standards-regulations.php",
}


# ────────────────────────────────────────────────────────────────────────────
# INTERNAL APPLICATION ACTIONS
# ────────────────────────────────────────────────────────────────────────────

INTERNAL_ACTIONS: Set[str] = {
    "patent_checklist",
    "supporting_documents",
    "tkdl_scan",
    "preparation_draft",
}


# ────────────────────────────────────────────────────────────────────────────
# ALL VALID ACTION IDS
# ────────────────────────────────────────────────────────────────────────────

VALID_ACTION_IDS: Set[str] = set(OFFICIAL_DESTINATIONS.keys()) | INTERNAL_ACTIONS


# ────────────────────────────────────────────────────────────────────────────
# ACTION METADATA
# ────────────────────────────────────────────────────────────────────────────

class ActionMetadata(BaseModel):
    """Full metadata for an action (ID + label + type + optional URL)"""
    id: str
    label: str
    type: str  # "external" or "internal"
    url: Optional[str] = None  # Only for external actions
    description: Optional[str] = None


ACTION_DEFINITIONS: Dict[str, ActionMetadata] = {
    # Official External Resources - Government Websites & Forms
    "patent_search": ActionMetadata(
        id="patent_search",
        label="Search Indian Patents",
        type="external",
        url=OFFICIAL_DESTINATIONS["patent_search"],
        description="Official IP India patent search database"
    ),
    "patent_filing": ActionMetadata(
        id="patent_filing",
        label="IP India e-Filing Portal",
        type="external",
        url=OFFICIAL_DESTINATIONS["patent_filing"],
        description="Official patent filing portal - IP India"
    ),
    "patent_forms": ActionMetadata(
        id="patent_forms",
        label="Official Patent Forms & Fees",
        type="external",
        url=OFFICIAL_DESTINATIONS["patent_forms"],
        description="Official IP India patent forms and official fees page"
    ),
    "ip_india_manual": ActionMetadata(
        id="ip_india_manual",
        label="Patent Office Manual",
        type="external",
        url=OFFICIAL_DESTINATIONS["ip_india_manual"],
        description="Official Manual for Patent Office Practice and Procedure"
    ),
    "nba_resources": ActionMetadata(
        id="nba_resources",
        label="National Biodiversity Authority",
        type="external",
        url=OFFICIAL_DESTINATIONS["nba_resources"],
        description="Official NBA website - biological resource compliance"
    ),
    "nba_access_guidelines": ActionMetadata(
        id="nba_access_guidelines",
        label="NBA Access Guidelines",
        type="external",
        url=OFFICIAL_DESTINATIONS["nba_access_guidelines"],
        description="Official NBA guidelines for biological resource access"
    ),
    "foscos": ActionMetadata(
        id="foscos",
        label="FoSCoS Portal",
        type="external",
        url=OFFICIAL_DESTINATIONS["foscos"],
        description="Official FSSAI FoSCoS portal for food safety compliance"
    ),
    "fssai_regulations": ActionMetadata(
        id="fssai_regulations",
        label="FSSAI Regulations",
        type="external",
        url=OFFICIAL_DESTINATIONS["fssai_regulations"],
        description="Official FSSAI Food Safety and Standards Regulations"
    ),

    # Internal Tools - Non-Official Helpers
    "patent_checklist": ActionMetadata(
        id="patent_checklist",
        label="Patent Preparation Checklist",
        type="internal",
        description="Internal preparation checklist (not an official form)"
    ),
    "supporting_documents": ActionMetadata(
        id="supporting_documents",
        label="View Cited Documents",
        type="internal",
        description="Review statutory documents cited in this answer"
    ),
    "tkdl_scan": ActionMetadata(
        id="tkdl_scan",
        label="Open TKDL Scanner",
        type="internal",
        description="Scan against Traditional Knowledge Digital Library"
    ),
    "preparation_draft": ActionMetadata(
        id="preparation_draft",
        label="Generate Preparation Draft",
        type="internal",
        description="Non-official preparation document for reference only"
    ),
}


# ────────────────────────────────────────────────────────────────────────────
# VALIDATION & RESOLUTION
# ────────────────────────────────────────────────────────────────────────────

def validate_action_ids(action_ids: List[str]) -> List[str]:
    """
    Validate a list of action IDs against the whitelist.
    Returns only valid IDs (unknown IDs are silently dropped).
    """
    return [aid for aid in action_ids if aid in VALID_ACTION_IDS]


def resolve_action_metadata(action_id: str) -> Optional[ActionMetadata]:
    """
    Resolve an action ID to its full metadata.
    Returns None if action ID is not whitelisted.
    """
    return ACTION_DEFINITIONS.get(action_id)


def get_action_suggestions(action_ids: List[str]) -> List[ActionMetadata]:
    """
    Convert a list of action IDs to full action metadata.
    Validates IDs and filters out unknown actions.
    """
    validated_ids = validate_action_ids(action_ids)
    return [resolve_action_metadata(aid) for aid in validated_ids if resolve_action_metadata(aid)]
