"""
Human IP Facilitator Escalation — PDF Dossier Generator
=========================================================
Generates a structured escalation PDF using reportlab (pure Python).
Uses ONLY standard Helvetica/Times fonts — no custom TTF files needed,
ensuring zero dependency issues on HuggingFace Spaces / Render free tier.
"""
import io
from datetime import datetime
from typing import Optional, List, Dict, Any

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    HRFlowable,
)

_BLUE   = colors.HexColor("#1e40af")
_LBLUE  = colors.HexColor("#dbeafe")
_SLATE  = colors.HexColor("#64748b")
_DARK   = colors.HexColor("#1f2937")
_GREY   = colors.HexColor("#374151")
_RED    = colors.HexColor("#dc2626")
_LRED   = colors.HexColor("#fef2f2")
_STRIPE = colors.HexColor("#f8fafc")
_BORDER = colors.HexColor("#e2e8f0")
_WHITE  = colors.white


def generate_escalation_pdf(
    messages: List[Dict[str, Any]],
    citations: Optional[List[Dict]] = None,
    session_id: Optional[str] = None,
) -> bytes:
    """
    Build and return a PDF dossier as raw bytes.
    Standard Helvetica fonts only — no TTF bundling.
    """
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        rightMargin=2*cm, leftMargin=2*cm,
        topMargin=2*cm, bottomMargin=2*cm,
    )

    S = getSampleStyleSheet()
    story: list = []

    # ── Style Definitions ──────────────────────────────────────────────────
    def ps(name, **kw):
        return ParagraphStyle(name, parent=S["Normal"], **kw)

    title_s   = ps("T",  fontSize=18, fontName="Helvetica-Bold", textColor=_BLUE,
                   alignment=TA_CENTER, spaceAfter=2)
    sub_s     = ps("S",  fontSize=9,  fontName="Helvetica",      textColor=_SLATE,
                   alignment=TA_CENTER, spaceAfter=2)
    section_s = ps("H",  fontSize=12, fontName="Helvetica-Bold", textColor=_BLUE,
                   spaceBefore=10, spaceAfter=4)
    body_s    = ps("B",  fontSize=9,  fontName="Helvetica",      textColor=_DARK,
                   leading=13, spaceAfter=4)
    label_s   = ps("L",  fontSize=9,  fontName="Helvetica-Bold", textColor=_GREY,
                   spaceAfter=2)
    disc_s    = ps("D",  fontSize=8,  fontName="Helvetica-Oblique", textColor=_RED,
                   backColor=_LRED, borderWidth=0.75, borderColor=_RED,
                   borderPadding=5, leading=12, spaceAfter=6)
    user_s    = ps("U",  fontSize=9,  fontName="Helvetica-Bold", textColor=_BLUE,
                   spaceAfter=1)
    ai_s      = ps("A",  fontSize=9,  fontName="Helvetica",      textColor=_DARK,
                   leading=13, leftIndent=10, backColor=_STRIPE,
                   borderWidth=0.5, borderColor=_BORDER, borderPadding=4,
                   spaceAfter=6)
    footer_s  = ps("F",  fontSize=8,  fontName="Helvetica",      textColor=_SLATE,
                   alignment=TA_CENTER)

    # ── Cover Header ───────────────────────────────────────────────────────
    story += [
        Paragraph("IP-SAKTI Sahayak", title_s),
        Paragraph("Human IP Facilitator — Escalation Dossier", sub_s),
        Paragraph("Ministry of Ayush | All India Institute of Ayurveda | PS ID: 26045", sub_s),
        Spacer(1, 0.25*cm),
        HRFlowable(width="100%", thickness=1.5, color=_BLUE),
        Spacer(1, 0.2*cm),
    ]

    # Metadata table
    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    meta = [
        ["Generated:", now],
        ["Session ID:", session_id or "N/A"],
        ["Status:", "ESCALATED — Awaiting Human IP Facilitator Review"],
    ]
    mt = Table(meta, colWidths=[3.2*cm, 12.8*cm])
    mt.setStyle(TableStyle([
        ("FONTNAME",  (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTNAME",  (1, 0), (1, -1), "Helvetica"),
        ("FONTSIZE",  (0, 0), (-1, -1), 9),
        ("TEXTCOLOR", (1, 2), (1, 2),   _RED),
        ("TOPPADDING",    (0, 0), (-1, -1), 2),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
    ]))
    story += [mt, Spacer(1, 0.25*cm)]

    # Disclaimer
    story.append(Paragraph(
        "LEGAL DISCLAIMER: This dossier is generated by an AI assistant for informational "
        "purposes only. It does NOT constitute legal advice. All information must be reviewed "
        "by a qualified IP attorney or the relevant statutory authority before any legal "
        "action is taken.",
        disc_s,
    ))



    # ── Chat Transcript ────────────────────────────────────────────────────
    if messages:
        story += [
            Paragraph("Chat Transcript", section_s),
            HRFlowable(width="100%", thickness=0.5, color=_LBLUE),
            Spacer(1, 0.1*cm),
        ]
        for msg in messages:
            role    = msg.get("role", "user")
            content = msg.get("content", "")[:1200]
            # Strip emoji that reportlab can't render with standard fonts
            content = _strip_emoji(content)
            label   = "User:" if role == "user" else "IP-SAKTI Sahayak (AI):"
            story.append(Paragraph(label, user_s))
            story.append(Paragraph(content, ai_s))

    # ── Statutory Citations ────────────────────────────────────────────────
    if citations:
        story += [
            Paragraph("Statutory Citations", section_s),
            HRFlowable(width="100%", thickness=0.5, color=_LBLUE),
            Spacer(1, 0.1*cm),
        ]
        hdr = [["#", "Source Document", "Page", "Excerpt"]]
        rows = [
            [
                str(i),
                cit.get("source", ""),
                str(cit.get("page", "")),
                cit.get("snippet", "")[:120] + "…",
            ]
            for i, cit in enumerate(citations[:10], 1)
        ]
        cit_t = Table(hdr + rows, colWidths=[0.7*cm, 5*cm, 1.3*cm, 9*cm])
        cit_t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), _BLUE),
            ("TEXTCOLOR",  (0, 0), (-1, 0), _WHITE),
            ("FONTNAME",   (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTNAME",   (0, 1), (-1, -1), "Helvetica"),
            ("FONTSIZE",   (0, 0), (-1, -1), 8),
            ("VALIGN",     (0, 0), (-1, -1), "TOP"),
            ("TOPPADDING",    (0, 0), (-1, -1), 3),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [_WHITE, _STRIPE]),
            ("GRID", (0, 0), (-1, -1), 0.25, _BORDER),
            ("WORDWRAP", (3, 1), (3, -1), True),
        ]))
        story.append(cit_t)

    # ── Footer ────────────────────────────────────────────────────────────
    story += [
        Spacer(1, 0.5*cm),
        HRFlowable(width="100%", thickness=1.0, color=_BLUE),
        Spacer(1, 0.15*cm),
        Paragraph(
            "This dossier has been escalated to a Human IP Facilitator for expert review. "
            "IP-SAKTI Sahayak | Ministry of Ayush | Problem Statement ID: 26045",
            footer_s,
        ),
    ]

    doc.build(story)
    return buf.getvalue()


def _strip_emoji(text: str) -> str:
    """Remove emoji characters that standard Helvetica cannot render."""
    import re
    emoji_pattern = re.compile(
        "[\U00010000-\U0010ffff"
        "\U0001F600-\U0001F64F"
        "\U0001F300-\U0001F5FF"
        "\U0001F680-\U0001F6FF"
        "\U00002702-\U000027B0"
        "\U000024C2-\U0001F251"
        "]+",
        flags=re.UNICODE,
    )
    return emoji_pattern.sub("", text)
