"use client";

import { X, AlertTriangle, Download, FileText } from "lucide-react";
import { useState } from "react";

interface PreparationDraftProps {
  onClose: () => void;
  context?: {
    query?: string;
    answer?: string;
    citations?: any[];
  };
}

export function PreparationDraft({ onClose, context }: PreparationDraftProps) {
  const [copied, setCopied] = useState(false);

  const generateDraftContent = () => {
    const date = new Date().toLocaleDateString('en-IN', {
      day: '2-digit',
      month: 'long',
      year: 'numeric'
    });

    return `
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                    NON-OFFICIAL PREPARATION DOCUMENT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

IMPORTANT NOTICE:
This document is AI-generated for informational purposes and is NOT an
official government filing or legal advice. It should be reviewed by a
qualified professional before use.

Generated by: IP-SAKTI Sahayak (AI Assistant)
Date: ${date}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

PREPARATION NOTES
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Query Context:
${context?.query || '[Not provided]'}

${context?.answer ? `
Relevant Legal Guidance:
${context.answer.substring(0, 1000)}${context.answer.length > 1000 ? '...' : ''}
` : ''}

${context?.citations && context.citations.length > 0 ? `
Referenced Sources:
${context.citations.map((c: any, i: number) => `${i + 1}. ${c.source} (Page ${c.page})`).join('\n')}
` : ''}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

APPLICANT INFORMATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Name of Applicant:          [Not provided]
Address:                    [Not provided]
Contact Details:            [Not provided]
Email:                      [Not provided]
Organization (if any):      [Not provided]

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

SUBJECT MATTER DETAILS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Title/Name:                 [Not provided]
Description:                [Not provided]
Category:                   [Not provided]
Intended Use:               [Not provided]

For Patent Applications:
  - Novel Features:         [Not provided]
  - Prior Art Considerations: [To be researched]
  - TKDL Search Status:     [Not completed]

For Biological Resources:
  - Resource Name:          [Not provided]
  - Source/Location:        [Not provided]
  - Access Permission:      [Not obtained]

For Regulatory Matters:
  - Regulatory Body:        [To be determined]
  - Required Approvals:     [To be identified]
  - Compliance Status:      [To be assessed]

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

NEXT STEPS CHECKLIST
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

☐ Consult with qualified IP attorney or legal professional
☐ Complete all required information fields marked [Not provided]
☐ Gather supporting documentation
☐ Verify compliance with applicable regulations
☐ Conduct thorough prior art search (for patents)
☐ Obtain necessary permissions and approvals
☐ Review and verify all technical and legal details
☐ Prepare official filing documents with professional assistance

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

DISCLAIMER
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

This preparation document is automatically generated based on limited
information and should not be used as a substitute for professional legal
advice or official government forms. All information marked [Not provided]
must be completed by the applicant with accurate details. The document does
not constitute a filing, application, or official submission to any
government authority.

For official filings, please:
1. Consult a qualified IP attorney or registered patent agent
2. Use official government forms and portals
3. Verify all legal requirements and procedures
4. Ensure compliance with applicable laws and regulations

Ministry of Ayush | All India Institute of Ayurveda
IP-SAKTI Sahayak - AI Assistant for Informational Purposes Only

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
`.trim();
  };

  const handleCopy = () => {
    const content = generateDraftContent();
    navigator.clipboard.writeText(content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const content = generateDraftContent();
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `preparation-draft-${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center z-50 p-4">
      <div className="bg-surface rounded-2xl shadow-2xl w-full max-w-4xl max-h-[90vh] flex flex-col border border-outline-variant/30">
        {/* Header */}
        <div className="flex items-center justify-between p-6 border-b border-outline-variant/30 bg-amber-50">
          <div className="flex items-center gap-3">
            <div className="bg-amber-500/10 p-2 rounded-lg">
              <AlertTriangle className="w-6 h-6 text-amber-700" />
            </div>
            <div>
              <h2 className="text-xl font-bold text-gray-900">
                Non-Official Preparation Document
              </h2>
              <p className="text-sm text-amber-700 font-semibold">
                For informational purposes only - Not a legal filing
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-2 rounded-lg hover:bg-gray-100 transition-colors"
          >
            <X className="w-5 h-5 text-gray-500" />
          </button>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto p-6">
          <div className="bg-amber-50 border-l-4 border-amber-500 p-4 mb-6">
            <div className="flex items-start gap-3">
              <AlertTriangle className="w-5 h-5 text-amber-700 flex-shrink-0 mt-0.5" />
              <div className="text-sm text-amber-900">
                <p className="font-semibold mb-1">Important Notice:</p>
                <p>
                  This is an AI-generated preparation document for reference only.
                  It is <strong>NOT</strong> an official government form or legal filing.
                  All information marked <code className="bg-amber-100 px-1 py-0.5 rounded">[Not provided]</code> must
                  be completed by you with accurate details. This document must be reviewed
                  by a qualified professional before use.
                </p>
              </div>
            </div>
          </div>

          <pre className="bg-gray-50 p-6 rounded-lg text-xs font-mono text-gray-800 overflow-x-auto border border-gray-200 whitespace-pre-wrap break-words">
            {generateDraftContent()}
          </pre>
        </div>

        {/* Footer */}
        <div className="flex items-center justify-between p-6 border-t border-outline-variant/30 bg-gray-50">
          <p className="text-sm text-gray-600">
            Generated by IP-SAKTI Sahayak • For informational purposes only
          </p>
          <div className="flex gap-3">
            <button
              onClick={handleCopy}
              className="inline-flex items-center gap-2 px-4 py-2 rounded-lg bg-white border border-gray-300 text-gray-700 hover:bg-gray-50 hover:border-gray-400 transition-all shadow-sm text-sm font-semibold"
            >
              <FileText className="w-4 h-4" />
              {copied ? "Copied!" : "Copy to Clipboard"}
            </button>
            <button
              onClick={handleDownload}
              className="inline-flex items-center gap-2 px-4 py-2 rounded-lg bg-blue-600 text-white hover:bg-blue-700 transition-all shadow-sm text-sm font-semibold"
            >
              <Download className="w-4 h-4" />
              Download as TXT
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
